/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapCategoriesDotxmlRouteImport } from './routes/sitemap-categories[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminAlmaSecure2026RouteImport } from './routes/_authenticated/admin-alma-secure-2026'
import { Route as AuthenticatedCabinetRouteImport } from './routes/_authenticated/cabinet'
import { Route as ApiCartRouteImport } from './routes/api/cart'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiShippingCalcRouteImport } from './routes/api/shipping-calc'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogSplatRouteImport } from './routes/catalog.$'
import { Route as SitemapProductsPageRouteImport } from './routes/sitemap-products.$page'
import { Route as AuthenticatedAdminAlmaSecure2026IndexRouteImport } from './routes/_authenticated/admin-alma-secure-2026.index'
import { Route as AuthenticatedAdminAlmaSecure2026AiRouteImport } from './routes/_authenticated/admin-alma-secure-2026.ai'
import { Route as AuthenticatedAdminAlmaSecure2026CompaniesRouteImport } from './routes/_authenticated/admin-alma-secure-2026.companies'
import { Route as AuthenticatedAdminAlmaSecure2026LeadsRouteImport } from './routes/_authenticated/admin-alma-secure-2026.leads'
import { Route as AuthenticatedAdminAlmaSecure2026LogsRouteImport } from './routes/_authenticated/admin-alma-secure-2026.logs'
import { Route as AuthenticatedAdminAlmaSecure2026ProductsRouteImport } from './routes/_authenticated/admin-alma-secure-2026.products'
import { Route as AuthenticatedAdminAlmaSecure2026SettingsRouteImport } from './routes/_authenticated/admin-alma-secure-2026.settings'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as ApiAdminCatalogSyncRouteImport } from './routes/api/admin/catalog-sync'
import { Route as ApiAuthOtpRequestRouteImport } from './routes/api/auth/otp-request'
import { Route as ApiCheckoutSubmitRouteImport } from './routes/api/checkout/submit'
import { Route as ApiConfiguratorSolveRouteImport } from './routes/api/configurator/solve'
import { Route as ApiDadataCityRouteImport } from './routes/api/dadata/city'
import { Route as ApiDadataPartyRouteImport } from './routes/api/dadata/party'
import { Route as ApiLeadsBulkRouteImport } from './routes/api/leads/bulk'
import { Route as ApiParserUploadRouteImport } from './routes/api/parser/upload'
import { Route as ApiPublicSendMailRouteImport } from './routes/api/public/send-mail'
import { Route as ApiQuizSubmitRouteImport } from './routes/api/quiz/submit'
import { Route as ApiUploadPresignedUrlRouteImport } from './routes/api/upload/presigned-url'
import { Route as ApiVisionIdentifyRouteImport } from './routes/api/vision/identify'
import { Route as AuthenticatedAdminAlmaSecure2026OrdersOrderIdRouteImport } from './routes/_authenticated/admin-alma-secure-2026.orders.$orderId'
import { Route as ApiPublicCadSplatRouteImport } from './routes/api/public/cad/$'
import { Route as ApiPublicErpRetryRouteImport } from './routes/api/public/erp/retry'
import { Route as ApiPublicErpStatusRouteImport } from './routes/api/public/erp/status'
import { Route as ApiPublicErpStockRouteImport } from './routes/api/public/erp/stock'
import { Route as ApiPublicWebhooksCarrierRouteImport } from './routes/api/public/webhooks/carrier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCategoriesDotxmlRoute = SitemapCategoriesDotxmlRouteImport.update({
  id: '/sitemap-categories.xml',
  path: '/sitemap-categories.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAlmaSecure2026Route =
  AuthenticatedAdminAlmaSecure2026RouteImport.update({
    id: '/admin-alma-secure-2026',
    path: '/admin-alma-secure-2026',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetRoute = AuthenticatedCabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCartRoute = ApiCartRouteImport.update({
  id: '/api/cart',
  path: '/api/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShippingCalcRoute = ApiShippingCalcRouteImport.update({
  id: '/api/shipping-calc',
  path: '/api/shipping-calc',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogSplatRoute = CatalogSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CatalogRoute,
} as any)
const SitemapProductsPageRoute = SitemapProductsPageRouteImport.update({
  id: '/sitemap-products/$page',
  path: '/sitemap-products/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAlmaSecure2026IndexRoute =
  AuthenticatedAdminAlmaSecure2026IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAlmaSecure2026Route,
  } as any)
const AuthenticatedAdminAlmaSecure2026AiRoute =
  AuthenticatedAdminAlmaSecure2026AiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => AuthenticatedAdminAlmaSecure2026Route,
  } as any)
const AuthenticatedAdminAlmaSecure2026CompaniesRoute =
  AuthenticatedAdminAlmaSecure2026CompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminAlmaSecure2026Route,
  } as any)
const AuthenticatedAdminAlmaSecure2026LeadsRoute =
  AuthenticatedAdminAlmaSecure2026LeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedAdminAlmaSecure2026Route,
  } as any)
const AuthenticatedAdminAlmaSecure2026LogsRoute =
  AuthenticatedAdminAlmaSecure2026LogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedAdminAlmaSecure2026Route,
  } as any)
const AuthenticatedAdminAlmaSecure2026ProductsRoute =
  AuthenticatedAdminAlmaSecure2026ProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminAlmaSecure2026Route,
  } as any)
const AuthenticatedAdminAlmaSecure2026SettingsRoute =
  AuthenticatedAdminAlmaSecure2026SettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminAlmaSecure2026Route,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAdminCatalogSyncRoute = ApiAdminCatalogSyncRouteImport.update({
  id: '/api/admin/catalog-sync',
  path: '/api/admin/catalog-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOtpRequestRoute = ApiAuthOtpRequestRouteImport.update({
  id: '/api/auth/otp-request',
  path: '/api/auth/otp-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutSubmitRoute = ApiCheckoutSubmitRouteImport.update({
  id: '/api/checkout/submit',
  path: '/api/checkout/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfiguratorSolveRoute = ApiConfiguratorSolveRouteImport.update({
  id: '/api/configurator/solve',
  path: '/api/configurator/solve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDadataCityRoute = ApiDadataCityRouteImport.update({
  id: '/api/dadata/city',
  path: '/api/dadata/city',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDadataPartyRoute = ApiDadataPartyRouteImport.update({
  id: '/api/dadata/party',
  path: '/api/dadata/party',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsBulkRoute = ApiLeadsBulkRouteImport.update({
  id: '/api/leads/bulk',
  path: '/api/leads/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParserUploadRoute = ApiParserUploadRouteImport.update({
  id: '/api/parser/upload',
  path: '/api/parser/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendMailRoute = ApiPublicSendMailRouteImport.update({
  id: '/api/public/send-mail',
  path: '/api/public/send-mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizSubmitRoute = ApiQuizSubmitRouteImport.update({
  id: '/api/quiz/submit',
  path: '/api/quiz/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadPresignedUrlRoute = ApiUploadPresignedUrlRouteImport.update({
  id: '/api/upload/presigned-url',
  path: '/api/upload/presigned-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionIdentifyRoute = ApiVisionIdentifyRouteImport.update({
  id: '/api/vision/identify',
  path: '/api/vision/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAlmaSecure2026OrdersOrderIdRoute =
  AuthenticatedAdminAlmaSecure2026OrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedAdminAlmaSecure2026Route,
  } as any)
const ApiPublicCadSplatRoute = ApiPublicCadSplatRouteImport.update({
  id: '/api/public/cad/$',
  path: '/api/public/cad/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicErpRetryRoute = ApiPublicErpRetryRouteImport.update({
  id: '/api/public/erp/retry',
  path: '/api/public/erp/retry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicErpStatusRoute = ApiPublicErpStatusRouteImport.update({
  id: '/api/public/erp/status',
  path: '/api/public/erp/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicErpStockRoute = ApiPublicErpStockRouteImport.update({
  id: '/api/public/erp/stock',
  path: '/api/public/erp/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksCarrierRoute =
  ApiPublicWebhooksCarrierRouteImport.update({
    id: '/api/public/webhooks/carrier',
    path: '/api/public/webhooks/carrier',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/admin-alma-secure-2026': typeof AuthenticatedAdminAlmaSecure2026RouteWithChildren
  '/cabinet': typeof AuthenticatedCabinetRoute
  '/api/cart': typeof ApiCartRoute
  '/api/search': typeof ApiSearchRoute
  '/api/shipping-calc': typeof ApiShippingCalcRoute
  '/catalog/$': typeof CatalogSplatRoute
  '/sitemap-products/$page': typeof SitemapProductsPageRoute
  '/catalog/': typeof CatalogIndexRoute
  '/admin-alma-secure-2026/ai': typeof AuthenticatedAdminAlmaSecure2026AiRoute
  '/admin-alma-secure-2026/companies': typeof AuthenticatedAdminAlmaSecure2026CompaniesRoute
  '/admin-alma-secure-2026/leads': typeof AuthenticatedAdminAlmaSecure2026LeadsRoute
  '/admin-alma-secure-2026/logs': typeof AuthenticatedAdminAlmaSecure2026LogsRoute
  '/admin-alma-secure-2026/products': typeof AuthenticatedAdminAlmaSecure2026ProductsRoute
  '/admin-alma-secure-2026/settings': typeof AuthenticatedAdminAlmaSecure2026SettingsRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/api/admin/catalog-sync': typeof ApiAdminCatalogSyncRoute
  '/api/auth/otp-request': typeof ApiAuthOtpRequestRoute
  '/api/checkout/submit': typeof ApiCheckoutSubmitRoute
  '/api/configurator/solve': typeof ApiConfiguratorSolveRoute
  '/api/dadata/city': typeof ApiDadataCityRoute
  '/api/dadata/party': typeof ApiDadataPartyRoute
  '/api/leads/bulk': typeof ApiLeadsBulkRoute
  '/api/parser/upload': typeof ApiParserUploadRoute
  '/api/public/send-mail': typeof ApiPublicSendMailRoute
  '/api/quiz/submit': typeof ApiQuizSubmitRoute
  '/api/upload/presigned-url': typeof ApiUploadPresignedUrlRoute
  '/api/vision/identify': typeof ApiVisionIdentifyRoute
  '/admin-alma-secure-2026/': typeof AuthenticatedAdminAlmaSecure2026IndexRoute
  '/admin-alma-secure-2026/orders/$orderId': typeof AuthenticatedAdminAlmaSecure2026OrdersOrderIdRoute
  '/api/public/cad/$': typeof ApiPublicCadSplatRoute
  '/api/public/erp/retry': typeof ApiPublicErpRetryRoute
  '/api/public/erp/status': typeof ApiPublicErpStatusRoute
  '/api/public/erp/stock': typeof ApiPublicErpStockRoute
  '/api/public/webhooks/carrier': typeof ApiPublicWebhooksCarrierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/cabinet': typeof AuthenticatedCabinetRoute
  '/api/cart': typeof ApiCartRoute
  '/api/search': typeof ApiSearchRoute
  '/api/shipping-calc': typeof ApiShippingCalcRoute
  '/catalog/$': typeof CatalogSplatRoute
  '/sitemap-products/$page': typeof SitemapProductsPageRoute
  '/catalog': typeof CatalogIndexRoute
  '/admin-alma-secure-2026/ai': typeof AuthenticatedAdminAlmaSecure2026AiRoute
  '/admin-alma-secure-2026/companies': typeof AuthenticatedAdminAlmaSecure2026CompaniesRoute
  '/admin-alma-secure-2026/leads': typeof AuthenticatedAdminAlmaSecure2026LeadsRoute
  '/admin-alma-secure-2026/logs': typeof AuthenticatedAdminAlmaSecure2026LogsRoute
  '/admin-alma-secure-2026/products': typeof AuthenticatedAdminAlmaSecure2026ProductsRoute
  '/admin-alma-secure-2026/settings': typeof AuthenticatedAdminAlmaSecure2026SettingsRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/api/admin/catalog-sync': typeof ApiAdminCatalogSyncRoute
  '/api/auth/otp-request': typeof ApiAuthOtpRequestRoute
  '/api/checkout/submit': typeof ApiCheckoutSubmitRoute
  '/api/configurator/solve': typeof ApiConfiguratorSolveRoute
  '/api/dadata/city': typeof ApiDadataCityRoute
  '/api/dadata/party': typeof ApiDadataPartyRoute
  '/api/leads/bulk': typeof ApiLeadsBulkRoute
  '/api/parser/upload': typeof ApiParserUploadRoute
  '/api/public/send-mail': typeof ApiPublicSendMailRoute
  '/api/quiz/submit': typeof ApiQuizSubmitRoute
  '/api/upload/presigned-url': typeof ApiUploadPresignedUrlRoute
  '/api/vision/identify': typeof ApiVisionIdentifyRoute
  '/admin-alma-secure-2026': typeof AuthenticatedAdminAlmaSecure2026IndexRoute
  '/admin-alma-secure-2026/orders/$orderId': typeof AuthenticatedAdminAlmaSecure2026OrdersOrderIdRoute
  '/api/public/cad/$': typeof ApiPublicCadSplatRoute
  '/api/public/erp/retry': typeof ApiPublicErpRetryRoute
  '/api/public/erp/status': typeof ApiPublicErpStatusRoute
  '/api/public/erp/stock': typeof ApiPublicErpStockRoute
  '/api/public/webhooks/carrier': typeof ApiPublicWebhooksCarrierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin-alma-secure-2026': typeof AuthenticatedAdminAlmaSecure2026RouteWithChildren
  '/_authenticated/cabinet': typeof AuthenticatedCabinetRoute
  '/api/cart': typeof ApiCartRoute
  '/api/search': typeof ApiSearchRoute
  '/api/shipping-calc': typeof ApiShippingCalcRoute
  '/catalog/$': typeof CatalogSplatRoute
  '/sitemap-products/$page': typeof SitemapProductsPageRoute
  '/catalog/': typeof CatalogIndexRoute
  '/_authenticated/admin-alma-secure-2026/ai': typeof AuthenticatedAdminAlmaSecure2026AiRoute
  '/_authenticated/admin-alma-secure-2026/companies': typeof AuthenticatedAdminAlmaSecure2026CompaniesRoute
  '/_authenticated/admin-alma-secure-2026/leads': typeof AuthenticatedAdminAlmaSecure2026LeadsRoute
  '/_authenticated/admin-alma-secure-2026/logs': typeof AuthenticatedAdminAlmaSecure2026LogsRoute
  '/_authenticated/admin-alma-secure-2026/products': typeof AuthenticatedAdminAlmaSecure2026ProductsRoute
  '/_authenticated/admin-alma-secure-2026/settings': typeof AuthenticatedAdminAlmaSecure2026SettingsRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/api/admin/catalog-sync': typeof ApiAdminCatalogSyncRoute
  '/api/auth/otp-request': typeof ApiAuthOtpRequestRoute
  '/api/checkout/submit': typeof ApiCheckoutSubmitRoute
  '/api/configurator/solve': typeof ApiConfiguratorSolveRoute
  '/api/dadata/city': typeof ApiDadataCityRoute
  '/api/dadata/party': typeof ApiDadataPartyRoute
  '/api/leads/bulk': typeof ApiLeadsBulkRoute
  '/api/parser/upload': typeof ApiParserUploadRoute
  '/api/public/send-mail': typeof ApiPublicSendMailRoute
  '/api/quiz/submit': typeof ApiQuizSubmitRoute
  '/api/upload/presigned-url': typeof ApiUploadPresignedUrlRoute
  '/api/vision/identify': typeof ApiVisionIdentifyRoute
  '/_authenticated/admin-alma-secure-2026/': typeof AuthenticatedAdminAlmaSecure2026IndexRoute
  '/_authenticated/admin-alma-secure-2026/orders/$orderId': typeof AuthenticatedAdminAlmaSecure2026OrdersOrderIdRoute
  '/api/public/cad/$': typeof ApiPublicCadSplatRoute
  '/api/public/erp/retry': typeof ApiPublicErpRetryRoute
  '/api/public/erp/status': typeof ApiPublicErpStatusRoute
  '/api/public/erp/stock': typeof ApiPublicErpStockRoute
  '/api/public/webhooks/carrier': typeof ApiPublicWebhooksCarrierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/catalog'
    | '/privacy'
    | '/reset-password'
    | '/sitemap-categories.xml'
    | '/sitemap.xml'
    | '/success'
    | '/terms'
    | '/admin-alma-secure-2026'
    | '/cabinet'
    | '/api/cart'
    | '/api/search'
    | '/api/shipping-calc'
    | '/catalog/$'
    | '/sitemap-products/$page'
    | '/catalog/'
    | '/admin-alma-secure-2026/ai'
    | '/admin-alma-secure-2026/companies'
    | '/admin-alma-secure-2026/leads'
    | '/admin-alma-secure-2026/logs'
    | '/admin-alma-secure-2026/products'
    | '/admin-alma-secure-2026/settings'
    | '/orders/$orderId'
    | '/api/admin/catalog-sync'
    | '/api/auth/otp-request'
    | '/api/checkout/submit'
    | '/api/configurator/solve'
    | '/api/dadata/city'
    | '/api/dadata/party'
    | '/api/leads/bulk'
    | '/api/parser/upload'
    | '/api/public/send-mail'
    | '/api/quiz/submit'
    | '/api/upload/presigned-url'
    | '/api/vision/identify'
    | '/admin-alma-secure-2026/'
    | '/admin-alma-secure-2026/orders/$orderId'
    | '/api/public/cad/$'
    | '/api/public/erp/retry'
    | '/api/public/erp/status'
    | '/api/public/erp/stock'
    | '/api/public/webhooks/carrier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/privacy'
    | '/reset-password'
    | '/sitemap-categories.xml'
    | '/sitemap.xml'
    | '/success'
    | '/terms'
    | '/cabinet'
    | '/api/cart'
    | '/api/search'
    | '/api/shipping-calc'
    | '/catalog/$'
    | '/sitemap-products/$page'
    | '/catalog'
    | '/admin-alma-secure-2026/ai'
    | '/admin-alma-secure-2026/companies'
    | '/admin-alma-secure-2026/leads'
    | '/admin-alma-secure-2026/logs'
    | '/admin-alma-secure-2026/products'
    | '/admin-alma-secure-2026/settings'
    | '/orders/$orderId'
    | '/api/admin/catalog-sync'
    | '/api/auth/otp-request'
    | '/api/checkout/submit'
    | '/api/configurator/solve'
    | '/api/dadata/city'
    | '/api/dadata/party'
    | '/api/leads/bulk'
    | '/api/parser/upload'
    | '/api/public/send-mail'
    | '/api/quiz/submit'
    | '/api/upload/presigned-url'
    | '/api/vision/identify'
    | '/admin-alma-secure-2026'
    | '/admin-alma-secure-2026/orders/$orderId'
    | '/api/public/cad/$'
    | '/api/public/erp/retry'
    | '/api/public/erp/status'
    | '/api/public/erp/stock'
    | '/api/public/webhooks/carrier'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/catalog'
    | '/privacy'
    | '/reset-password'
    | '/sitemap-categories.xml'
    | '/sitemap.xml'
    | '/success'
    | '/terms'
    | '/_authenticated/admin-alma-secure-2026'
    | '/_authenticated/cabinet'
    | '/api/cart'
    | '/api/search'
    | '/api/shipping-calc'
    | '/catalog/$'
    | '/sitemap-products/$page'
    | '/catalog/'
    | '/_authenticated/admin-alma-secure-2026/ai'
    | '/_authenticated/admin-alma-secure-2026/companies'
    | '/_authenticated/admin-alma-secure-2026/leads'
    | '/_authenticated/admin-alma-secure-2026/logs'
    | '/_authenticated/admin-alma-secure-2026/products'
    | '/_authenticated/admin-alma-secure-2026/settings'
    | '/_authenticated/orders/$orderId'
    | '/api/admin/catalog-sync'
    | '/api/auth/otp-request'
    | '/api/checkout/submit'
    | '/api/configurator/solve'
    | '/api/dadata/city'
    | '/api/dadata/party'
    | '/api/leads/bulk'
    | '/api/parser/upload'
    | '/api/public/send-mail'
    | '/api/quiz/submit'
    | '/api/upload/presigned-url'
    | '/api/vision/identify'
    | '/_authenticated/admin-alma-secure-2026/'
    | '/_authenticated/admin-alma-secure-2026/orders/$orderId'
    | '/api/public/cad/$'
    | '/api/public/erp/retry'
    | '/api/public/erp/status'
    | '/api/public/erp/stock'
    | '/api/public/webhooks/carrier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapCategoriesDotxmlRoute: typeof SitemapCategoriesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuccessRoute: typeof SuccessRoute
  TermsRoute: typeof TermsRoute
  ApiCartRoute: typeof ApiCartRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiShippingCalcRoute: typeof ApiShippingCalcRoute
  SitemapProductsPageRoute: typeof SitemapProductsPageRoute
  ApiAdminCatalogSyncRoute: typeof ApiAdminCatalogSyncRoute
  ApiAuthOtpRequestRoute: typeof ApiAuthOtpRequestRoute
  ApiCheckoutSubmitRoute: typeof ApiCheckoutSubmitRoute
  ApiConfiguratorSolveRoute: typeof ApiConfiguratorSolveRoute
  ApiDadataCityRoute: typeof ApiDadataCityRoute
  ApiDadataPartyRoute: typeof ApiDadataPartyRoute
  ApiLeadsBulkRoute: typeof ApiLeadsBulkRoute
  ApiParserUploadRoute: typeof ApiParserUploadRoute
  ApiPublicSendMailRoute: typeof ApiPublicSendMailRoute
  ApiQuizSubmitRoute: typeof ApiQuizSubmitRoute
  ApiUploadPresignedUrlRoute: typeof ApiUploadPresignedUrlRoute
  ApiVisionIdentifyRoute: typeof ApiVisionIdentifyRoute
  ApiPublicCadSplatRoute: typeof ApiPublicCadSplatRoute
  ApiPublicErpRetryRoute: typeof ApiPublicErpRetryRoute
  ApiPublicErpStatusRoute: typeof ApiPublicErpStatusRoute
  ApiPublicErpStockRoute: typeof ApiPublicErpStockRoute
  ApiPublicWebhooksCarrierRoute: typeof ApiPublicWebhooksCarrierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-categories.xml': {
      id: '/sitemap-categories.xml'
      path: '/sitemap-categories.xml'
      fullPath: '/sitemap-categories.xml'
      preLoaderRoute: typeof SitemapCategoriesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-alma-secure-2026': {
      id: '/_authenticated/admin-alma-secure-2026'
      path: '/admin-alma-secure-2026'
      fullPath: '/admin-alma-secure-2026'
      preLoaderRoute: typeof AuthenticatedAdminAlmaSecure2026RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet': {
      id: '/_authenticated/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof AuthenticatedCabinetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/cart': {
      id: '/api/cart'
      path: '/api/cart'
      fullPath: '/api/cart'
      preLoaderRoute: typeof ApiCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shipping-calc': {
      id: '/api/shipping-calc'
      path: '/api/shipping-calc'
      fullPath: '/api/shipping-calc'
      preLoaderRoute: typeof ApiShippingCalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/$': {
      id: '/catalog/$'
      path: '/$'
      fullPath: '/catalog/$'
      preLoaderRoute: typeof CatalogSplatRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/sitemap-products/$page': {
      id: '/sitemap-products/$page'
      path: '/sitemap-products/$page'
      fullPath: '/sitemap-products/$page'
      preLoaderRoute: typeof SitemapProductsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-alma-secure-2026/': {
      id: '/_authenticated/admin-alma-secure-2026/'
      path: '/'
      fullPath: '/admin-alma-secure-2026/'
      preLoaderRoute: typeof AuthenticatedAdminAlmaSecure2026IndexRouteImport
      parentRoute: typeof AuthenticatedAdminAlmaSecure2026Route
    }
    '/_authenticated/admin-alma-secure-2026/ai': {
      id: '/_authenticated/admin-alma-secure-2026/ai'
      path: '/ai'
      fullPath: '/admin-alma-secure-2026/ai'
      preLoaderRoute: typeof AuthenticatedAdminAlmaSecure2026AiRouteImport
      parentRoute: typeof AuthenticatedAdminAlmaSecure2026Route
    }
    '/_authenticated/admin-alma-secure-2026/companies': {
      id: '/_authenticated/admin-alma-secure-2026/companies'
      path: '/companies'
      fullPath: '/admin-alma-secure-2026/companies'
      preLoaderRoute: typeof AuthenticatedAdminAlmaSecure2026CompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminAlmaSecure2026Route
    }
    '/_authenticated/admin-alma-secure-2026/leads': {
      id: '/_authenticated/admin-alma-secure-2026/leads'
      path: '/leads'
      fullPath: '/admin-alma-secure-2026/leads'
      preLoaderRoute: typeof AuthenticatedAdminAlmaSecure2026LeadsRouteImport
      parentRoute: typeof AuthenticatedAdminAlmaSecure2026Route
    }
    '/_authenticated/admin-alma-secure-2026/logs': {
      id: '/_authenticated/admin-alma-secure-2026/logs'
      path: '/logs'
      fullPath: '/admin-alma-secure-2026/logs'
      preLoaderRoute: typeof AuthenticatedAdminAlmaSecure2026LogsRouteImport
      parentRoute: typeof AuthenticatedAdminAlmaSecure2026Route
    }
    '/_authenticated/admin-alma-secure-2026/products': {
      id: '/_authenticated/admin-alma-secure-2026/products'
      path: '/products'
      fullPath: '/admin-alma-secure-2026/products'
      preLoaderRoute: typeof AuthenticatedAdminAlmaSecure2026ProductsRouteImport
      parentRoute: typeof AuthenticatedAdminAlmaSecure2026Route
    }
    '/_authenticated/admin-alma-secure-2026/settings': {
      id: '/_authenticated/admin-alma-secure-2026/settings'
      path: '/settings'
      fullPath: '/admin-alma-secure-2026/settings'
      preLoaderRoute: typeof AuthenticatedAdminAlmaSecure2026SettingsRouteImport
      parentRoute: typeof AuthenticatedAdminAlmaSecure2026Route
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/admin/catalog-sync': {
      id: '/api/admin/catalog-sync'
      path: '/api/admin/catalog-sync'
      fullPath: '/api/admin/catalog-sync'
      preLoaderRoute: typeof ApiAdminCatalogSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/otp-request': {
      id: '/api/auth/otp-request'
      path: '/api/auth/otp-request'
      fullPath: '/api/auth/otp-request'
      preLoaderRoute: typeof ApiAuthOtpRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/submit': {
      id: '/api/checkout/submit'
      path: '/api/checkout/submit'
      fullPath: '/api/checkout/submit'
      preLoaderRoute: typeof ApiCheckoutSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/configurator/solve': {
      id: '/api/configurator/solve'
      path: '/api/configurator/solve'
      fullPath: '/api/configurator/solve'
      preLoaderRoute: typeof ApiConfiguratorSolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dadata/city': {
      id: '/api/dadata/city'
      path: '/api/dadata/city'
      fullPath: '/api/dadata/city'
      preLoaderRoute: typeof ApiDadataCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dadata/party': {
      id: '/api/dadata/party'
      path: '/api/dadata/party'
      fullPath: '/api/dadata/party'
      preLoaderRoute: typeof ApiDadataPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/bulk': {
      id: '/api/leads/bulk'
      path: '/api/leads/bulk'
      fullPath: '/api/leads/bulk'
      preLoaderRoute: typeof ApiLeadsBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parser/upload': {
      id: '/api/parser/upload'
      path: '/api/parser/upload'
      fullPath: '/api/parser/upload'
      preLoaderRoute: typeof ApiParserUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-mail': {
      id: '/api/public/send-mail'
      path: '/api/public/send-mail'
      fullPath: '/api/public/send-mail'
      preLoaderRoute: typeof ApiPublicSendMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quiz/submit': {
      id: '/api/quiz/submit'
      path: '/api/quiz/submit'
      fullPath: '/api/quiz/submit'
      preLoaderRoute: typeof ApiQuizSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/presigned-url': {
      id: '/api/upload/presigned-url'
      path: '/api/upload/presigned-url'
      fullPath: '/api/upload/presigned-url'
      preLoaderRoute: typeof ApiUploadPresignedUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision/identify': {
      id: '/api/vision/identify'
      path: '/api/vision/identify'
      fullPath: '/api/vision/identify'
      preLoaderRoute: typeof ApiVisionIdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-alma-secure-2026/orders/$orderId': {
      id: '/_authenticated/admin-alma-secure-2026/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin-alma-secure-2026/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedAdminAlmaSecure2026OrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedAdminAlmaSecure2026Route
    }
    '/api/public/cad/$': {
      id: '/api/public/cad/$'
      path: '/api/public/cad/$'
      fullPath: '/api/public/cad/$'
      preLoaderRoute: typeof ApiPublicCadSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/erp/retry': {
      id: '/api/public/erp/retry'
      path: '/api/public/erp/retry'
      fullPath: '/api/public/erp/retry'
      preLoaderRoute: typeof ApiPublicErpRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/erp/status': {
      id: '/api/public/erp/status'
      path: '/api/public/erp/status'
      fullPath: '/api/public/erp/status'
      preLoaderRoute: typeof ApiPublicErpStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/erp/stock': {
      id: '/api/public/erp/stock'
      path: '/api/public/erp/stock'
      fullPath: '/api/public/erp/stock'
      preLoaderRoute: typeof ApiPublicErpStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/carrier': {
      id: '/api/public/webhooks/carrier'
      path: '/api/public/webhooks/carrier'
      fullPath: '/api/public/webhooks/carrier'
      preLoaderRoute: typeof ApiPublicWebhooksCarrierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminAlmaSecure2026RouteChildren {
  AuthenticatedAdminAlmaSecure2026AiRoute: typeof AuthenticatedAdminAlmaSecure2026AiRoute
  AuthenticatedAdminAlmaSecure2026CompaniesRoute: typeof AuthenticatedAdminAlmaSecure2026CompaniesRoute
  AuthenticatedAdminAlmaSecure2026LeadsRoute: typeof AuthenticatedAdminAlmaSecure2026LeadsRoute
  AuthenticatedAdminAlmaSecure2026LogsRoute: typeof AuthenticatedAdminAlmaSecure2026LogsRoute
  AuthenticatedAdminAlmaSecure2026ProductsRoute: typeof AuthenticatedAdminAlmaSecure2026ProductsRoute
  AuthenticatedAdminAlmaSecure2026SettingsRoute: typeof AuthenticatedAdminAlmaSecure2026SettingsRoute
  AuthenticatedAdminAlmaSecure2026IndexRoute: typeof AuthenticatedAdminAlmaSecure2026IndexRoute
  AuthenticatedAdminAlmaSecure2026OrdersOrderIdRoute: typeof AuthenticatedAdminAlmaSecure2026OrdersOrderIdRoute
}

const AuthenticatedAdminAlmaSecure2026RouteChildren: AuthenticatedAdminAlmaSecure2026RouteChildren =
  {
    AuthenticatedAdminAlmaSecure2026AiRoute:
      AuthenticatedAdminAlmaSecure2026AiRoute,
    AuthenticatedAdminAlmaSecure2026CompaniesRoute:
      AuthenticatedAdminAlmaSecure2026CompaniesRoute,
    AuthenticatedAdminAlmaSecure2026LeadsRoute:
      AuthenticatedAdminAlmaSecure2026LeadsRoute,
    AuthenticatedAdminAlmaSecure2026LogsRoute:
      AuthenticatedAdminAlmaSecure2026LogsRoute,
    AuthenticatedAdminAlmaSecure2026ProductsRoute:
      AuthenticatedAdminAlmaSecure2026ProductsRoute,
    AuthenticatedAdminAlmaSecure2026SettingsRoute:
      AuthenticatedAdminAlmaSecure2026SettingsRoute,
    AuthenticatedAdminAlmaSecure2026IndexRoute:
      AuthenticatedAdminAlmaSecure2026IndexRoute,
    AuthenticatedAdminAlmaSecure2026OrdersOrderIdRoute:
      AuthenticatedAdminAlmaSecure2026OrdersOrderIdRoute,
  }

const AuthenticatedAdminAlmaSecure2026RouteWithChildren =
  AuthenticatedAdminAlmaSecure2026Route._addFileChildren(
    AuthenticatedAdminAlmaSecure2026RouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAlmaSecure2026Route: typeof AuthenticatedAdminAlmaSecure2026RouteWithChildren
  AuthenticatedCabinetRoute: typeof AuthenticatedCabinetRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAlmaSecure2026Route:
    AuthenticatedAdminAlmaSecure2026RouteWithChildren,
  AuthenticatedCabinetRoute: AuthenticatedCabinetRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CatalogRouteChildren {
  CatalogSplatRoute: typeof CatalogSplatRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogSplatRoute: CatalogSplatRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapCategoriesDotxmlRoute: SitemapCategoriesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuccessRoute: SuccessRoute,
  TermsRoute: TermsRoute,
  ApiCartRoute: ApiCartRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiShippingCalcRoute: ApiShippingCalcRoute,
  SitemapProductsPageRoute: SitemapProductsPageRoute,
  ApiAdminCatalogSyncRoute: ApiAdminCatalogSyncRoute,
  ApiAuthOtpRequestRoute: ApiAuthOtpRequestRoute,
  ApiCheckoutSubmitRoute: ApiCheckoutSubmitRoute,
  ApiConfiguratorSolveRoute: ApiConfiguratorSolveRoute,
  ApiDadataCityRoute: ApiDadataCityRoute,
  ApiDadataPartyRoute: ApiDadataPartyRoute,
  ApiLeadsBulkRoute: ApiLeadsBulkRoute,
  ApiParserUploadRoute: ApiParserUploadRoute,
  ApiPublicSendMailRoute: ApiPublicSendMailRoute,
  ApiQuizSubmitRoute: ApiQuizSubmitRoute,
  ApiUploadPresignedUrlRoute: ApiUploadPresignedUrlRoute,
  ApiVisionIdentifyRoute: ApiVisionIdentifyRoute,
  ApiPublicCadSplatRoute: ApiPublicCadSplatRoute,
  ApiPublicErpRetryRoute: ApiPublicErpRetryRoute,
  ApiPublicErpStatusRoute: ApiPublicErpStatusRoute,
  ApiPublicErpStockRoute: ApiPublicErpStockRoute,
  ApiPublicWebhooksCarrierRoute: ApiPublicWebhooksCarrierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
